
services:
  auth-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=your_secret_key
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres
  score-service:
    build: .
    ports:
      - "8001:8000"
    environment:
      - JWT_SECRET=your_secret_key
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres
  leaderboard-service:
    build: .
    ports:
      - "8002:8000"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=leaderboard
      - POSTGRES_PASSWORD=ppassword
      - POSTGRES_DB=leaderboard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  celery:
    build: .
    command: celery -A tasks.celery worker --loglevel=info
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres
volumes:
  postgres_data:
