services:
  user-service:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/user:/app
  game-service:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/game:/app
  score-service:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/score:/app
  leaderboard-service:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/leaderboard:/app
  global-record-service:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/global_record:/app
  admin-service:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/admin:/app
