deprecated_features.permit.management_metrics_collection = true
 deprecated_features.permit.transient_nonexcl_queues = true 
 deprecated_features.permit.global_qos = true 
 cluster_formation.peer_discovery_backend = classic_config 
 #cluster_formation.classic_config.nodes.1 = rabbit@localhost 
 log.console.level = warning 
 log.default.level = info 
 log.file.level = info